routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});


Route::get('/', 'HomeController@index')
    ->name('public.home');

Route::get('/course', 'HomeController@index')
    ->name('public.course.list');


Route::get('/news', 'HomeController@contact')
    ->name('public.news');

Route::get('/contact', 'HomeController@contact')
    ->name('public.contact');

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');

Auth::routes();

Route::get('/home', 'HomeController@Home');



Route::resource('categories', 'CategoryController');

Route::resource('courses', 'CourseController');



Route::resource('types', 'TypeController');



Route::resource('levels', 'LevelController');

Route::resource('languages', 'LanguageController');

Route::resource('userDetails', 'User_detailController');

Route::resource('studentSubscriptions', 'Student_subscriptionController');

Route::resource('courseHighlights', 'Course_highlightController');

Route::resource('users', 'UserController');

Route::resource('items', 'ItemController');

app/Models/Course_highlight.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Course_highlight
 * @package App\Models
 * @version January 10, 2020, 5:34 am UTC
 *
 * @property integer id_course
 * @property integer id_category
 * @property integer id_level
 * @property integer id_language
 * @property integer id_type
 * @property string beginning
 * @property number duration
 * @property integer number_of_lesson
 */
class Course_highlight extends Model
{
    use SoftDeletes;

    public $table = 'course_highlights';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'id_course',
        'id_category',
        'id_level',
        'id_language',
        'id_type',
        'beginning',
        'duration',
        'number_of_lesson'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'id_course' => 'integer',
        'id_category' => 'integer',
        'id_level' => 'integer',
        'id_language' => 'integer',
        'id_type' => 'integer',
        'beginning' => 'date',
        'duration' => 'double',
        'number_of_lesson' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'id_level' => 'required',
        'id_language' => 'required',
        'id_type' => 'required',
        'beginning' => 'required',
        'duration' => 'required'
    ];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     **/
    public function course()
    {
        return $this->hasOne(\App\Models\Course::class, 'id', 'Course_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function levels()
    {
        return $this->belongsTo(\App\Models\Level::class, 'id', 'Level_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function types()
    {
        return $this->belongsTo(\App\Models\Type::class, 'id', 'Type_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function categories()
    {
        return $this->belongsTo(\App\Models\Category::class, 'id', 'Category_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function languages()
    {
        return $this->belongsTo(\App\Models\Language::class, 'id', 'Language_id');
    }
    
}

app/Http/Controllers/Course_highlightController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCourse_highlightRequest;
use App\Http\Requests\UpdateCourse_highlightRequest;
use App\Repositories\Course_highlightRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class Course_highlightController extends AppBaseController
{
    /** @var  Course_highlightRepository */
    private $courseHighlightRepository;

    public function __construct(Course_highlightRepository $courseHighlightRepo)
    {
        $this->courseHighlightRepository = $courseHighlightRepo;
    }

    /**
     * Display a listing of the Course_highlight.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $courseHighlights = $this->courseHighlightRepository->all();

        return view('course_highlights.index')
            ->with('courseHighlights', $courseHighlights);
    }

    /**
     * Show the form for creating a new Course_highlight.
     *
     * @return Response
     */
    public function create()
    {
        return view('course_highlights.create');
    }

    /**
     * Store a newly created Course_highlight in storage.
     *
     * @param CreateCourse_highlightRequest $request
     *
     * @return Response
     */
    public function store(CreateCourse_highlightRequest $request)
    {
        $input = $request->all();

        $courseHighlight = $this->courseHighlightRepository->create($input);

        Flash::success('Course Highlight saved successfully.');

        return redirect(route('courseHighlights.index'));
    }

    /**
     * Display the specified Course_highlight.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $courseHighlight = $this->courseHighlightRepository->find($id);

        if (empty($courseHighlight)) {
            Flash::error('Course Highlight not found');

            return redirect(route('courseHighlights.index'));
        }

        return view('course_highlights.show')->with('courseHighlight', $courseHighlight);
    }

    /**
     * Show the form for editing the specified Course_highlight.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $courseHighlight = $this->courseHighlightRepository->find($id);

        if (empty($courseHighlight)) {
            Flash::error('Course Highlight not found');

            return redirect(route('courseHighlights.index'));
        }

        return view('course_highlights.edit')->with('courseHighlight', $courseHighlight);
    }

    /**
     * Update the specified Course_highlight in storage.
     *
     * @param int $id
     * @param UpdateCourse_highlightRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCourse_highlightRequest $request)
    {
        $courseHighlight = $this->courseHighlightRepository->find($id);

        if (empty($courseHighlight)) {
            Flash::error('Course Highlight not found');

            return redirect(route('courseHighlights.index'));
        }

        $courseHighlight = $this->courseHighlightRepository->update($request->all(), $id);

        Flash::success('Course Highlight updated successfully.');

        return redirect(route('courseHighlights.index'));
    }

    /**
     * Remove the specified Course_highlight from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $courseHighlight = $this->courseHighlightRepository->find($id);

        if (empty($courseHighlight)) {
            Flash::error('Course Highlight not found');

            return redirect(route('courseHighlights.index'));
        }

        $this->courseHighlightRepository->delete($id);

        Flash::success('Course Highlight deleted successfully.');

        return redirect(route('courseHighlights.index'));
    }
}

resources/views/course_highlights/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('courseHighlights.index') !!}">Course Highlight</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Course Highlight</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'courseHighlights.store']) !!}

                                   @include('course_highlights.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/course_highlights/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('courseHighlights.index') !!}">Course Highlight</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Course Highlight</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($courseHighlight, ['route' => ['courseHighlights.update', $courseHighlight->id], 'method' => 'patch']) !!}

                              @include('course_highlights.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/course_highlights/fields.blade.php
<!-- Id Course Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_course', 'Course:') !!}
    {!! Form::number('id_course', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Category Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_category', 'Category:') !!}
    {!! Form::number('id_category', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Level Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_level', 'Level:') !!}
    {!! Form::select('id_level', ['1' => 'Premiere Annee', '2' => 'Deuxieme Annee', '3' => 'Troisieme annee', '4' => 'Master 1', '5' => 'master 2'], null, ['class' => 'form-control']) !!}
</div>

<!-- Id Language Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_language', 'Language:') !!}
    {!! Form::select('id_language', ['1' => 'English', '2' => 'French'], null, ['class' => 'form-control']) !!}
</div>

<!-- Id Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_type', 'Type:') !!}
    {!! Form::select('id_type', ['1' => 'Video online', '2' => 'Distance learning', '3' => 'Presence Learning'], null, ['class' => 'form-control']) !!}
</div>

<!-- Beginning Field -->
<div class="form-group col-sm-6">
    {!! Form::label('beginning', 'Beginning:') !!}
    {!! Form::date('beginning', null, ['class' => 'form-control','id'=>'beginning']) !!}
</div>

@section('scripts')
   <script type="text/javascript">
           $('#beginning').datetimepicker({
               format: 'YYYY-MM-DD HH:mm:ss',
               useCurrent: true,
               icons: {
                   up: "icon-arrow-up-circle icons font-2xl",
                   down: "icon-arrow-down-circle icons font-2xl"
               },
               sideBySide: true
           })
       </script>
@endsection

<!-- Duration Field -->
<div class="form-group col-sm-6">
    {!! Form::label('duration', 'Duration:') !!}
    {!! Form::number('duration', null, ['class' => 'form-control']) !!}
</div>

<!-- Number Of Lesson Field -->
<div class="form-group col-sm-6">
    {!! Form::label('number_of_lesson', 'Number Of Lesson:') !!}
    {!! Form::number('number_of_lesson', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('courseHighlights.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/course_highlights/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Course Highlights</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             Course_highlights
                             <a class="float-right" href="{{ route('courseHighlights.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('course_highlights.table')
                              <div class="float-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/course_highlights/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('courseHighlights.index') }}">Course Highlight</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('courseHighlights.index') }}" class="btn btn-light float-right">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('course_highlights.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/course_highlights/show_fields.blade.php
<div class="course-intro">
    <div class="listing-box clearfix">
        <h5>Course Highlight for : {{$courseHighlight->id_course}}</h5>
        <ul class="listing-box-list">

            <li>
                <div class="row gap-10">
                    <div class="col-xs-5 col-sm-6"><i class="fa fa-info mr-5"></i> {!! Form::label('id_category', 'Category:') !!}</div>
                    <div class="col-xs-7 col-sm-6 text-right font600">{{ $courseHighlight->id_category }}</div>
                </div>
            </li>
            <li>
                <div class="row gap-10">
                    <div class="col-xs-5 col-sm-6"><i class="fa fa-bars mr-5"></i> {!! Form::label('id_level', 'Level:') !!}</div>
                    @if($courseHighlight->id_level = 1)
                    <div class="col-xs-7 col-sm-6 text-right font600">Premiere annee</div>
                        @elseif($courseHighlight->id_level = 2)
                        <div class="col-xs-7 col-sm-6 text-right font600">Deuxieme annee</div>
                    @elseif($courseHighlight->id_level = 3)
                        <div class="col-xs-7 col-sm-6 text-right font600">Troisieme annee</div>
                    @elseif($courseHighlight->id_level = 4)
                        <div class="col-xs-7 col-sm-6 text-right font600">Master One</div>
                    @elseif($courseHighlight->id_level = 5)
                        <div class="col-xs-7 col-sm-6 text-right font600">Master Two</div>
                    @endif
                </div>
            </li>
            <li>
                <div class="row gap-10">
                    <div class="col-xs-5 col-sm-6"><i class="fa fa-language"></i> Language :</div>
                   @if( $courseHighlight->id_language = 1)
                    <div class="col-xs-7 col-sm-6 text-right font600">English</div>
                    @elseif($courseHighlight->id_language = 2)
                        <div class="col-xs-7 col-sm-6 text-right font600">French</div>
                    @endif
                </div>
            </li>
            <li>
                <div class="row gap-10">
                    <div class="col-xs-5 col-sm-6"><i class="fa fa-clock mr-5"></i> Duration</div>
                    <div class="col-xs-7 col-sm-6 text-right font600">{{ $courseHighlight->duration }} Hours</div>
                </div>
            </li>
            <li>
                <div class="row gap-10">
                    <div class="col-xs-5 col-sm-5"><i class="fa fa-calendar mr-5"></i> {!! Form::label('beginning', 'Beginning:') !!}</div>
                    <div class="col-xs-7 col-sm-7 text-right font600">{{ $courseHighlight->beginning }}</div>
                </div>
            </li>
            <li>
                <div class="row gap-10">
                    <div class="col-xs-5 col-sm-5"><i class="fa fa-pen-nib mr-5"></i> {!! Form::label('number_of_lesson', 'Lesson:') !!}</div>
                    <div class="col-xs-7 col-sm-7 text-right font600"> {{ $courseHighlight->number_of_lesson }} lessons</div>
                </div>
            </li>
            <li>
                <div class="row gap-10">
                    <div class="col-xs-5 col-sm-5"><i class="fa fa-file-video mr-5"></i> Type</div>
                    @if( $courseHighlight->id_type = 1)
                    <div class="col-xs-7 col-sm-7 text-right font600"> Video online</div>
                        @elseif($courseHighlight->id_type = 3)
                        <div class="col-xs-7 col-sm-7 text-right font600"> Presence Learning</div>
                    @elseif($courseHighlight->id_type = 2)
                        <div class="col-xs-7 col-sm-7 text-right font600"> Distance Learning</div>
                        @endif
                </div>
            </li>

            <li>
                <div class="row gap-10">
                    <div class="col-xs-5 col-sm-5">
                    <a href="{{ route('courseHighlights.show', [$courseHighlight->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                    </div>
                    <div class="col-xs-5 col-sm-5">
                    <a href="{{ route('courseHighlights.edit', [$courseHighlight->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                    </div>
                </div>

            </li>
        </ul>
    </div>
</div>



{{--
<!-- Id Course Field -->
<div class="form-group">
    {!! Form::label('id_course', 'Course:') !!}
    <p>{{ $courseHighlight->id_course }}</p>
</div>

<!-- Id Category Field -->
<div class="form-group">
    {!! Form::label('id_category', 'Category:') !!}
    <p>{{ $courseHighlight->id_category }}</p>
</div>

<!-- Id Level Field -->
<div class="form-group">
    {!! Form::label('id_level', 'Level:') !!}
    <p>{{ $courseHighlight->id_level }}</p>
</div>

<!-- Id Language Field -->
<div class="form-group">
    {!! Form::label('id_language', 'Language:') !!}
    <p>{{ $courseHighlight->id_language }}</p>
</div>

<!-- Id Type Field -->
<div class="form-group">
    {!! Form::label('id_type', 'Type:') !!}
    <p>{{ $courseHighlight->id_type }}</p>
</div>

<!-- Beginning Field -->
<div class="form-group">
    {!! Form::label('beginning', 'Beginning:') !!}
    <p>{{ $courseHighlight->beginning }}</p>
</div>

<!-- Duration Field -->
<div class="form-group">
    {!! Form::label('duration', 'Duration:') !!}
    <p>{{ $courseHighlight->duration }}</p>
</div>

<!-- Number Of Lesson Field -->
<div class="form-group">
    {!! Form::label('number_of_lesson', 'Number Of Lesson:') !!}
    <p>{{ $courseHighlight->number_of_lesson }}</p>
</div>



--}}

resources/views/course_highlights/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="courseHighlights-table">
        <thead>
            <th>Course</th>
        <th>Category</th>
        <th>Level</th>
        <th>Language</th>
        <th>Type</th>
        <th>Beginning</th>
        <th>Duration</th>
        <th>Number Of Lesson</th>
            <th colspan="3">Action</th>
        </thead>
        <tbody>
        @foreach($courseHighlights as $courseHighlight)
            <tr>
                <td>{{ $courseHighlight->id_course }}</td>
            <td>{{ $courseHighlight->id_category }}</td>
            <td>{{ $courseHighlight->id_level }}</td>
            <td>{{ $courseHighlight->id_language }}</td>
            <td>{{ $courseHighlight->id_type }}</td>
            <td>{{ $courseHighlight->beginning }}</td>
            <td>{{ $courseHighlight->duration }}</td>
            <td>{{ $courseHighlight->number_of_lesson }}</td>
                <td>
                    {!! Form::open(['route' => ['courseHighlights.destroy', $courseHighlight->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('courseHighlights.show', [$courseHighlight->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('courseHighlights.edit', [$courseHighlight->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>